// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0L5GAwN5QrbVJRu2vuyzey5ogItUYZwg',
    appId: '1:1053995691405:web:e23da6cd525a1c835261c4',
    messagingSenderId: '1053995691405',
    projectId: 'pingmee-first-step-auth',
    authDomain: 'pingmee-first-step-auth.firebaseapp.com',
    storageBucket: 'pingmee-first-step-auth.firebasestorage.app',
    measurementId: 'G-BTG38SEDRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6eyb0IyjxJG84BGcnHz-ExvJCNaxkEvQ',
    appId: '1:1053995691405:android:d9d33547cad211845261c4',
    messagingSenderId: '1053995691405',
    projectId: 'pingmee-first-step-auth',
    storageBucket: 'pingmee-first-step-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0yQNneATcN-rypFxWZNqtZ-Ie9OKuMsg',
    appId: '1:1053995691405:ios:e25ae813499df2195261c4',
    messagingSenderId: '1053995691405',
    projectId: 'pingmee-first-step-auth',
    storageBucket: 'pingmee-first-step-auth.firebasestorage.app',
    iosBundleId: 'com.example.pingFiles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0yQNneATcN-rypFxWZNqtZ-Ie9OKuMsg',
    appId: '1:1053995691405:ios:e25ae813499df2195261c4',
    messagingSenderId: '1053995691405',
    projectId: 'pingmee-first-step-auth',
    storageBucket: 'pingmee-first-step-auth.firebasestorage.app',
    iosBundleId: 'com.example.pingFiles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0L5GAwN5QrbVJRu2vuyzey5ogItUYZwg',
    appId: '1:1053995691405:web:e376f07f1159bd0a5261c4',
    messagingSenderId: '1053995691405',
    projectId: 'pingmee-first-step-auth',
    authDomain: 'pingmee-first-step-auth.firebaseapp.com',
    storageBucket: 'pingmee-first-step-auth.firebasestorage.app',
    measurementId: 'G-3Z07YYKW6N',
  );
}
